apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-playground
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/pulgamecanica/iot2
    targetRevision: HEAD
    path: app
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
